### ISSUE TITLE
File Not Found Error on Termux

### ISSUE THREAD

**Issue by abidovii** [fulvius31/OneShot#3]
sudo python OneShot/oneshot.py -i wlan0 --iface-down -K
[*] Running wpa_supplicant…
[*] BSSID not specified (--bssid) — scanning for available networks
Network marks: Possibly vulnerable | WPS locked | Already stored
Networks list:
#    BSSID              ESSID                     Sec.     PWR  WSC device name             WSC model
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/OneShot/oneshot.py", line 1251, in <module>
    network_info = scanner.prompt_network()
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/OneShot/oneshot.py", line 1046, in prompt_network
    networks = self.iw_scanner()
               ^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/OneShot/oneshot.py", line 1038, in iw_scanner
    elif (self.vuln_list and (model in self.vuln_list)) or self.checkvuln_from_pin_csv("./pins.csv", network['BSSID']):
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/OneShot/oneshot.py", line 875, in checkvuln_from_pin_csv
    with open(pin_file_path, newline='') as csvfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './pins.csv'

**Comment by antoniosolismz** [comment]
Do you have the "pins.csv" file in your directory?

**Comment by Sassech** [comment]
I have the same error, but it only happens when I type 'sudo python OneShot/oneshot.py -i wlan0 --iface-down -K'. However, if I enter into the folder 'cd OneShot', then I execute 'sudo python oneshot.py -i wlan0 --iface-down -K', it works fine.
![Screenshot_2024-01-31-02-04-06-704_com termux](https://github.com/fulvius31/OneShot/assets/137150849/1e6be427-e5fd-4611-84af-a27b2b2852b7)
![Screenshot_2024-01-31-02-04-26-727_com termux](https://github.com/fulvius31/OneShot/assets/137150849/cfd937a8-229e-47c9-a455-717a288447fc)
